---
- hosts: all
  become: true

  tasks:
  - name: Prepare Install folder
    sudo: true
    action: shell sudo mkdir -p /tmp/nagios

- name: Install a .deb package from the internet
  apt:
    deb: https://www.claudiokuenzler.com/downloads/nrpe/nagios-nrpe-server_3.2.1-cae1_amd64.buster.deb
